<h2>Quiz 1 : Penggabungan Data</h2>

- Sebutkan perbedaan antara full outer join, inner join, dan left join

Jawaban :

<h2>Quiz 2 : Penggabungan Data</h2>

Pada quiz no 2 ini gunakan data 'names1881.csv' dan 'names1981.csv', data ini berisi nama bayi yang lahir pada tahun 1881 atau 1981 di Amerika.

- Baca data tersebut dengan memberikan nama column 'Name', 'Gender', 'Count'.
- Tunjukan jumlah dimensi dari data 'names1881.csv' dan 'names1981.csv'
- Gabungkan kedua data tersebut berdasarkan sumbu baris
- Tunjukan jumlah dimensi dari data setelah di gabungkan.

In [0]:
import pandas as pd
# read data
df1 = pd.read_csv(........, .......)
df2 = pd.read_csv(........, .......)

# periksa dimensi dari kedua data
print("Jumlah Dimensi data 'names1881.csv' :")
........

# gabungkan data
print("Jumlah Baris data 'names1981.csv' :")
df = ........
print(df)

# periksa dimensi data hasil gabungan
print("Jumlah dimensi data setelah penggabungan : ")
.........

Expected Result : 

Jumlah Dimensi data 'names1881.csv' : 

(1935, 3)

Jumlah Baris data 'names1981.csv' :

(19455, 3)

![alt text](https://drive.google.com/uc?id=1jMCAdLrcJubjufydZBnzdQkYqDS3Klat)

Jumlah dimensi data setelah penggabungan : 

(21390, 3)

<h2>Quiz 3 : Penggabungan Data</h2>

Lakukan jenis penggabungan data full outer join, inner join, left outer join dan right outer join pada kedua data berikut :

In [0]:
import pandas as pd

data1 = {
    'id' : [1, 2, 3, 4],
    'Feature1' : ['a1', 'a2', 'a3', 'a4'],
    'Feature2' : ['b1', 'b2', 'b3', 'b4']
}

data2 = {
    'id' : [3, 4, 5 ,6, 7],
    'Feature3' : ['c1', 'c2', 'c3', 'c4', 'c5']
}

df1= pd.DataFrame(data1)
df2= pd.DataFrame(data2)

print(df1)
print(df2)

   id Feature1 Feature2
0   1       a1       b1
1   2       a2       b2
2   3       a3       b3
3   4       a4       b4
   id Feature3
0   3       c1
1   4       c2
2   5       c3
3   6       c4
4   7       c5

In [0]:
# join data
df_outer_join = ............
print(df_outer_join)

df_inner_join = ..........
print(df_inner_join)

df_left_join = ...........
print(df_left_join)

df_right_join = ...........
print(df_right_join)

Expected Result :

![alt text](https://drive.google.com/uc?id=1kUpkzWh3Y-X_1H1QXHiccdHf4YjqXsDu)

![alt text](https://drive.google.com/uc?id=1ojoAC2oX9P3ZHl0lS3RXipd7gShLOmmC)

![alt text](https://drive.google.com/uc?id=12jDnQzIosn6dizVwl2nPMX1IhhyEZ4FA)

![alt text](https://drive.google.com/uc?id=11znqscNsVZ-cHY-PPgoHEBDWyc6XRtAL)

<h2>Quiz 4 : Penggabungan Data berbeda label column Key</h2>

Lakukan jenis penggabungan inner join untuk 2 data yang memiliki nama column key yang berbeda ini :

In [0]:
data1 = {
    'key_data1' : [1, 2, 3, 4],
    'Feature1' : ['a1', 'a2', 'a3', 'a4'],
    'Feature2' : ['b1', 'b2', 'b3', 'b4']
}

data2 = {
    'key_data2' : [3, 4, 5 ,6, 7],
    'Feature3' : ['c1', 'c2', 'c3', 'c4', 'c5']
}

df1= pd.DataFrame(data1)
df2= pd.DataFrame(data2)

print(df1)
print(df2)

   key_data1 Feature1 Feature2
0          1       a1       b1
1          2       a2       b2
2          3       a3       b3
3          4       a4       b4
   key_data2 Feature3
0          3       c1
1          4       c2
2          5       c3
3          6       c4
4          7       c5

In [0]:
# Gabungkan kedua data tersebut
df_gabung = ...................

df_gabung

Expected Result :

![alt text](https://drive.google.com/uc?id=1uBiVOPnqns4al88FDc0ENIeTzIxP4wxH)